/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Query_DB;
public class App {
    public static void main(String[] args) {
       Panel DB_Panel = new Panel();
       DB_Panel.setVisible(true);
    }
}
